# Generated by Django 5.2.4 on 2025-09-05 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_rtchat", "0003_chatgroup_is_private_chatgroup_members_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(
                default="o4kg9ZgG4FzatxX6kkxozP", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="chat_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
